name: lingo_manage
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  loading_animation_widget: ^1.3.0
  google_fonts: ^8.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/app_icon.png
    - assets/ilustration/ilustration_1.png
